// Generated by cmake/GenerateMechType.cmake — do not edit.
// Source: PJ_REGISTER_MECHANISM(ClassName) in /home/zhf/noetix_ws/repos/pjsol/src/core/mechanisms
#pragma once

namespace pjsol {

enum class MechType {
    M2RSS1Ux,
    M2RSS1Uxi,
};

inline constexpr const char* name(MechType type) noexcept {
    switch (type) {
    case MechType::M2RSS1Ux:
        return "M2RSS1Ux";
    case MechType::M2RSS1Uxi:
        return "M2RSS1Uxi";
    }
    return nullptr;
}

} // namespace pjsol
