<?xml version="1.0"?>
<package format="2">
    <name>rl_controllers</name>
    <version>0.0.0</version>
    <description>The rl_controllers packages. reference: sustech_clear_lab/legged_rl</description>
    <maintainer email="huaxinghuang@noetixrobotics.com">Noetix Team</maintainer>
    <license>BSD</license>
    <author email="huaxinghuang@noetixrobotics.com">Noetix Team</author>

    <buildtool_depend>catkin</buildtool_depend>

    <build_depend>cmake_clang_tools</build_depend>
    <depend>roscpp</depend>
    <depend>legged_common</depend>

    <depend>controller_interface</depend>
    <depend>controller_manager_msgs</depend>
    <exec_depend>controller_manager</exec_depend>
    <depend>dynamic_reconfigure</depend>
    <depend>geometry_msgs</depend>
    <depend>hardware_interface</depend>
    <depend>kdl_parser</depend>
    <depend>sensor_msgs</depend>
    <depend>std_msgs</depend>
    <depend>rviz</depend>
    <depend>robot_state_publisher</depend>
    <depend>tf</depend>
    <depend>urdf</depend>
    <exec_depend>rospy</exec_depend>
    <exec_depend>actionlib</exec_depend>
    <exec_depend>rostopic</exec_depend>
    <exec_depend>rosservice</exec_depend>
    <exec_depend>genpy</exec_depend>
    <exec_depend>python3-serial</exec_depend>
    <exec_depend>joy</exec_depend>

    <export>
        <controller_interface plugin="${prefix}/rl_controllers_plugins.xml"/>
    </export>
</package>
